on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install AWS Cli
      run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - name: Install AWS Cli
      run: unzip awscliv2.zip
    - name: Install AWS Cli
      run: sudo ./aws/install

    - name: Install AWS Lightsail
      run: curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"

    - name: Make Lightsail Plugin Executable
      run: sudo chmod +x /usr/local/bin/lightsailctl

    - name: Build the Image
      run: docker build -t cf-deployment -f Dockerfile .

    - name: Login to AWS and push to Lightsail 
      run: aws lightsail push-container-image --region us-east-1 --service-name container-service-1 --label cf-deployment-1 --image cf-deployment:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}